sudo: required
language: node_js
node_js:
  - 'lts/*'
before_install:
  - npm i -g npm@latest
install: npm ci
script: npm run lint
branches:
  only:
    - master
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
